name: sewa-sansar
services:
  backend:
    container_name: sewa-sansar-dev
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: sewa-sansar:dev
    env_file:
      - ./backend/.env
    ports: ["4000:4000"]
    environment:
      - NODE_ENV=development
    networks:
      - mariadb-net
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - node_modules/
            - dist/
        - action: rebuild
          path: ./backend/package.json
        - action: rebuild
          path: ./backend/Dockerfile

networks:
  mariadb-net:
    external: true
